all:
  hosts:
    vm1:
      ansible_host: 192.168.122.100
    vm2:
      ansible_host: 192.168.122.101
    vm3:
      ansible_host: 192.168.122.102
  vars:
    ansible_user: vmuser
    ansible_password: vmuser
    ansible_become_password: vmuser
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"