image:
  registry: docker.arvancloud.ir
  repository: bitnami/postgresql
  tag: 17.2.0-debian-12-r1
  pullPolicy: IfNotPresent

auth:
  enablePostgresUser: true
  postgresPassword: "postgres"
  username: "dbuser"
  password: "dbuser"
  database: "db"
  replicationUsername: repl_user
  replicationPassword: "repl_password"

architecture: replication
replication:
  applicationName: cluster

containerPorts:
  postgresql: 5432

readReplicas:
  replicaCount: 1

metrics:
  enabled: true
  image:
    registry: docker.arvancloud.ir
    repository: bitnami/postgres-exporter
    tag: 0.16.0-debian-12-r1
    pullPolicy: IfNotPresent
