prometheus:
  prometheusSpec:
    # Disable matching the release: prometheus-stack on service monitors
    serviceMonitorSelectorNilUsesHelmValues: false
    # Disable matching the release: prometheus-stack on prometheus rules
    ruleSelectorNilUsesHelmValues: false
alertmanager:
  enabled: false
pushgateway:
  enabled: false
grafana:
  enabled: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "grafana-dashboards-kubernetes"
          orgId: 1
          folder: "Kubernetes"
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
        - name: "arvan-service-dashboards"
          orgId: 1
          folder: "Arvan Service"
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/arvan-service-dashboards
  dashboards:
    grafana-dashboards-kubernetes:
      k8s-system-api-server:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
        token: ""
      k8s-system-coredns:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
        token: ""
      k8s-views-global:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
        token: ""
      k8s-views-namespaces:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
        token: ""
      k8s-views-nodes:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
        token: ""
      k8s-views-pods:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
        token: ""
    arvan-service-dashboards:
      arvan-app-dashboard:
        url: https://raw.githubusercontent.com/FeryET/arvan-interview-task/refs/heads/main/helm/charts/service/files/dashboard.json
        token: ""
server:
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
