---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: "{{ .Release.Namespace }}"
data:
  # Data Base Config
  DB_HOST: "{{ .Values.db.host }}"
  DB_USER: "{{ .Values.db.user }}"
  DB_PASSWORD: "{{ .Values.db.password }}"
  DB_NAME: "{{ .Values.db.name }}"
  DB_PORT: "{{ .Values.db.port }}"
  DB_TABLE_NAME: "{{ .Values.db.tableName }}"
  DB_MAX_OPEN_CONNS: "1024"
  DB_MAX_IDLE_CONNS: "512"
  DB_MAX_LIFETIME_SECS: "20"
  DB_MAX_IDLETIME_SECS: "10"
  # Server Config
  SERVER_PORT: "{{ .Values.server.port }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-table
  namespace: "{{ .Release.Namespace }}"
data:
  init-table.sql: |
    \c db;
    CREATE TABLE IF NOT EXISTS {{ .Values.db.tableName }} (
        id SERIAL PRIMARY KEY,             -- Unique identifier for each entry
        ip VARCHAR(64),                    -- Stores IP addresses, max length of IPv6 is 45 characters
        country VARCHAR(64)                -- Stores country names, max length 64 to cover the longest names, the United Kingdom is 56 characters.
    );
