apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: arvan-app
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: arvan-app
spec:
  selector:
    matchLabels:
      app: arvan-app
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
