replicas: 1
server:
  port: 3333
resources:
  cpus: 500m
  memory: 256Mi

db:
  host: postgresql-primary
  port: 5432
  user: postgres
  password: postgres
  name: db
  tableName: "ip_cache"

image:
  repository: docker.arvancloud.ir/feryet/arvan-service
  tag: 0.1.0
  pullPolicy: IfNotPresent
