helmDefaults:
  cleanupOnFail: true
  createNamespace: true
  kubeContext: k3s

releases:
  - name: prometheus-stack
    namespace: production
    chart: "./base-charts/kube-prometheus-stack"
    version: 66.3.0
    disableValidation: true
    values:
      - "./values/prometheus.yml"

  - name: loki
    namespace: production
    chart: "./base-charts/loki"
    version: 6.22.0
    values:
      - "./values/loki.yml"

  - name: postgresql
    namespace: production
    chart: "./base-charts/postgresql"
    version: 16.2.3
    values:
      - "./values/postgres.yml"
    needs:
      - prometheus-stack
