{
 "title": "Arvan App Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (path)",
     "legendFormat": "path: {{ path  }}"
    }
   ]
  },
  {
   "title": "95th Percentile Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, path))",
     "legendFormat": "path: {{ path }} "
    }
   ]
  },
  {
   "title": "Response Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{pod=~\"^arvan.*\"}[5m])) by (path, status)",
     "legendFormat": "path: {{ path }} - status: {{ status }}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "milicores" } },
   "targets": [
    {
     "expr": "sum by (pod ) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"arvan-app.*\"}[5m])) * 1000",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"arvan-app.*\"} / (1024 * 1024))",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}